version: '2'
services:
  db:
    image: pheasanthunters/db2express-c:latest
    privileged: true    
    ports:
      - "50000:50000"
    command: /start-db.sh
 
  tomee:
    depends_on:
      - db
    image: pheasanthunters/tomee1.7.4:latest
    links:
      - db
    ports:
      - "8080:8080"
