VAGRANTFILE_API_VERSION = "2"

#
# L'installazione prevede: 
# - Docker
# - Docker-compose
#

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	# Ubuntu trusty 64 VirtualBox.
	config.vm.box = "ubuntu/trusty64"

	# cartella per le risorse condivise 
	config.vm.synced_folder "./shared/", "/home/vagrant/shared", :mount_options => ["dmode=777", "fmode=777"]

	config.vm.hostname = "server"    

        config.vm.provider "virtualbox" do |v| 
            v.memory = 2048
        end 

        config.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh', auto_correct: true
        config.ssh.forward_agent = true

        # provisioning con bash 
     	config.vm.provision :shell, :inline => 'apt-get update'

	config.vm.provision :shell, path: "./shared/scripts/setup-docker.sh"
        # aggiunge vagrant al gruppo di docker (richiede un reboot?) 
        config.vm.provision :shell, :inline => 'usermod -aG docker vagrant'        
        # installa anche docker-compose 
        config.vm.provision :shell, path: "./shared/scripts/setup-docker-compose.sh"

        config.vm.provision :shell, 
            inline: "echo  'configurazione vm server completata'"

end
